meta_product_name: "RESPET"
meta_title: "A voice for all animals"
meta_description: "An application that aims to help animals in need, and provide a platform for animal lovers."
meta_image: "logo-respet.png" # should exist in `app/assets/images/`
